export const panelHtml = `<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Career Ops</title>
<style>
:root{color-scheme:light dark;font-family:system-ui,sans-serif;color:light-dark(#20372e,#e7eee9);background:light-dark(#fafbf8,#17221d)}*{box-sizing:border-box}body{margin:0;padding:20px}header{display:flex;align-items:center;justify-content:space-between;gap:12px}h1{margin:0;font-size:22px;font-weight:650}p{font-size:13px;line-height:1.5;opacity:.8}button,input,select{font:inherit;padding:9px 12px;border:1px solid light-dark(#ccd6cc,#44584b);border-radius:7px;background:light-dark(white,#25372c);color:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:wait}form{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}input{flex:1;min-width:130px}button.primary{background:#196447;color:#fff;border-color:#196447}table{width:100%;border-collapse:collapse;text-align:left;font-size:13px}th,td{padding:12px 8px;border-bottom:1px solid light-dark(#e1e7df,#344b3c);vertical-align:top}th{font-weight:550;opacity:.65}.role{display:block;opacity:.75;font-size:12px;margin-top:3px}.tag{display:inline-block;padding:3px 8px;border-radius:12px;background:light-dark(#e8f0e6,#2a4433);white-space:nowrap}.summary{display:flex;gap:20px;font-size:13px;margin:18px 0}.summary b{font-size:24px;display:block}nav{display:flex;gap:8px;justify-content:flex-end;margin-top:16px}#status{min-height:20px}.table-wrap{overflow:auto}#status.error{color:light-dark(#a32824,#ffb3ad)}@media(max-width:480px){body{padding:12px}th,td{padding:10px 5px}header button{font-size:12px}}
</style></head><body>
<header><h1>Career Ops</h1><button id="refresh" type="button">Yenile</button></header>
<p>Vercel uygulamasındaki başvuru listesi</p>
<form id="filters"><input id="query" aria-label="Şirket veya rol ara" placeholder="Şirket veya rol ara"><select id="statusFilter" aria-label="Başvuru durumu"><option value="">Tüm durumlar</option><option>Applied</option><option>Interview</option><option>Offer</option><option>Rejected</option><option>Pending</option></select><button class="primary" type="submit">Ara</button></form>
<div id="status" role="status" aria-live="polite">Başvurular yükleniyor…</div>
<div class="summary"><div><b id="applicationsCount">—</b>Başvuru</div><div><b id="inboxCount">—</b>Gelen ilan</div></div>
<div class="table-wrap"><table><thead><tr><th>Şirket / Rol</th><th>Durum</th><th>Skor</th></tr></thead><tbody id="rows"></tbody></table></div>
<nav><button id="previous" type="button" disabled>Önceki</button><button id="next" type="button" disabled>Sonraki</button></nav>
<p id="snapshotNote">Neon’daki kayıtlar okunur; yerel değişiklikler henüz aktarılmamış olabilir. Bu panel salt okunurdur.</p>
<script>
const pending=new Map();let sequence=0,offset=0,nextOffset=null,received=false,busy=false;
const statusEl=document.getElementById('status');
function send(method,params){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('ChatGPT bağlantısı yanıt vermedi.'));},20000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');});}
function notify(method,params){window.parent.postMessage({jsonrpc:'2.0',method,params},'*');}
function render(result){received=true;if(result?.isError){statusEl.className='error';statusEl.textContent=result.content?.[0]?.text||'Liste okunamadı.';return;}const data=result?.structuredContent;if(!data?.applications)return;offset=data.pagination?.offset||0;nextOffset=data.pagination?.nextOffset??null;statusEl.className='';statusEl.textContent=data.applications.length?'':'Bu filtreyle başvuru bulunamadı.';document.getElementById('applicationsCount').textContent=data.totals.applications;document.getElementById('inboxCount').textContent=data.totals.inbox;const rows=document.getElementById('rows');rows.replaceChildren();for(const row of data.applications){const tr=document.createElement('tr');const title=document.createElement('td');title.textContent=String(row.company||'—');const role=document.createElement('span');role.className='role';role.textContent=String(row.role||'');title.append(role);const state=document.createElement('td');const tag=document.createElement('span');tag.className='tag';tag.textContent=String(row.status||'—');state.append(tag);const score=document.createElement('td');score.textContent=String(row.score??'—');tr.append(title,state,score);rows.append(tr);}document.getElementById('previous').disabled=offset===0;document.getElementById('next').disabled=nextOffset===null;notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight});}
window.addEventListener('message',event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=='2.0')return;if(message.id!==undefined&&pending.has(message.id)){const request=pending.get(message.id);pending.delete(message.id);clearTimeout(request.timer);message.error?request.reject(new Error(message.error.message)):request.resolve(message.result);return;}if(message.method==='ui/notifications/tool-result')render(message.params);if(message.method==='ui/notifications/tool-cancelled'){statusEl.textContent='İşlem iptal edildi.';}if(message.method==='ui/notifications/host-context-changed'){const theme=message.params?.theme;if(theme==='dark'||theme==='light')document.documentElement.style.colorScheme=theme;}});
async function load(page=0){if(busy)return;busy=true;statusEl.textContent='Başvurular okunuyor…';document.getElementById('refresh').disabled=true;try{render(await send('tools/call',{name:'career_ops_pipeline',arguments:{query:document.getElementById('query').value,status:document.getElementById('statusFilter').value,limit:25,offset:page}}));}catch(error){statusEl.className='error';statusEl.textContent=error.message;}finally{busy=false;document.getElementById('refresh').disabled=false;}}
document.getElementById('filters').addEventListener('submit',event=>{event.preventDefault();load(0);});document.getElementById('refresh').onclick=()=>load(offset);document.getElementById('previous').onclick=()=>load(Math.max(0,offset-25));document.getElementById('next').onclick=()=>{if(nextOffset!==null)load(nextOffset);};
send('ui/initialize',{appInfo:{name:'career-ops',version:'1.0.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(result=>{notify('ui/notifications/initialized',{});const theme=result?.hostContext?.theme;if(theme==='dark'||theme==='light')document.documentElement.style.colorScheme=theme;setTimeout(()=>{if(!received)load(0);},350);}).catch(()=>{statusEl.textContent='Bu paneli ChatGPT’de Career Ops eklentisinden aç.';});
</script></body></html>`;
